### PR TITLE
Add ClassStructureSniff

### PR DESCRIPTION
**Pull request by grongor**

### CODE REVIEW

**Comment by simPod** [comment]
Budeme to pridavat do rulesetu?

**Comment by simPod** [comment]
Included automatically, consider question to be invalid :P

**Comment by simPod** [comment]
This placement is marked as invalid and IMO shouldn't:

```php
    private function __construct($value) { ... }

    public static function fromString(string $value) : self { ... }
```

**Comment by grongor** [comment]
cc @janedbal

**Pull request merged**
